import {Book } from './book.model';

export interface OrderItem {
  bookId: string;                 // Reference to Books collection
  title: string;                  // Book title (snapshot for order history)
  quantity: number;               // Number of copies ordered (min: 1)
  price: number;                  // Price at the time of order (snapshot)
  // Populated field
  book?: Book;                    // Populated book details when needed
}

export interface Address {
  fullName: string;
  phone: string;
  addressLine: string;
  city: string;
  state: string;
  pincode: string;
  country: string;
}

export interface PaymentInfo {
  method: 'CARD' | 'UPI' | 'COD' | 'WALLET';
  status: 'pending' | 'paid' | 'failed' | 'refunded';
  razorpayOrderId?: string;       // from createOrder() — before payment
  razorpayPaymentId?: string;     // from frontend — after payment
  razorpaySignature?: string;     // store after verification for audit
  paidAt?: Date;
}

export interface Pricing {
  subtotal: number;
  discount: number;               // default: 0
  deliveryCharges: number;        // default: 0
  tax:number,
  total: number;                  // required
}

export interface ShippingInfo {
  carrier?: string;               // e.g., "FedEx", "UPS", "DHL"
  trackingNumber?: string;        // Tracking number from carrier
  estimatedDeliveryDate?: Date;   // Estimated delivery date
  shippedAt?: Date;               // When order was shipped
}

export interface Order {
  _id: string;                    // Auto-generated by MongoDB
  userId: string;                 // Reference to Users collection
  items: OrderItem[];
  shippingAddress: Address;       // Shipping address snapshot
  paymentInfo: PaymentInfo;
  pricing: Pricing;
  orderStatus: 'placed' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
  shippingInfo?: ShippingInfo;
  deliveredAt?: Date;             // When order was delivered
  createdAt: Date;
  updatedAt: Date;
}