const mongoose = require('mongoose');

const books= mongoose.Schema(
    {            // Auto-generated by MongoDB
        title: {                     // Book title
          type: String,
          required: true,
          trim: true
        },
        author: {                    // Author name(s)
          type: String,
          required: true
        },
        description: String,       // Detailed book description
        ISBN: { type: String, unique: true },
        price: {                     // Book price (in USD)
          type: Number,
          required: true,
          min: 0
        },
        discount: { type: Number, default: 0 },
        category: {                  // Genre/category
          type: String,
          enum: ["Fiction", "Non-Fiction", "Sci-Fi", "Biography", "Romance", "Mystery", "Fantasy"],
          required: true
        },
        tags: [String],              // Array of tags for better searchability
        stock: {                     // Available quantity
          type: Number,
          required: true,
          min: 0,
          default: 0
        },
        language: String,
        publisher: String,
        publishedDate: Date,

        image: [{                     // Book cover image URL
          type: String,
          default: "default-book.jpg"
        }],
        ratingAvg: { type: Number, default: 0 },
        ratingCount: { type: Number, default: 0 },
        createdAt: {                 // When book was added
          type: Date,
          default: Date.now
        },
        updatedAt: Date              // Last update timestamp
      }
);

const Book = mongoose.model("Book", books);

module.exports = Book;
