const mongoose = require('mongoose');
const orders=mongoose.Schema(
    {          // Auto-generated by MongoDB
        userId: {                      // Reference to Users collection
          type: mongoose.Schema.Types.ObjectId,
          ref: "User",
          required: true
        },
        orderItems: [                // List of ordered books
          {
            bookId: {                  // Reference to Books collection
              type: mongoose.Schema.Types.ObjectId,
              ref: "Book",
              required: true
            },
            title: String,             // Book title (snapshot for order history)
            quantity: {              // Number of copies ordered
              type: Number,
              required: true,
              min: 1
            },
            price: Number            // Price at the time of order (snapshot)
          }
        ],
        shippingAddress: {  
         fullName: String,
         phone: String,
         addressLine: String,
         city: String,
         state: String,
         pincode: String,
         country: String
        },
      
        paymentInfo: {
        method: {
         type: String,
         enum: ["CARD", "UPI", "COD", "WALLET"],
         required: true
        },
        status: {
         type: String,
         enum: ["pending", "completed", "failed"],
         default: "pending"
       },
        transactionId: String
    },
        
        paymentResult: {             // Payment gateway response (if applicable)
          id: String,                // Transaction ID
          status: String,            // Payment status (e.g., "completed")
          update_time: String,       // When payment was processed
          email: String              // Payer's email
        },
        pricing: {
    subtotal: Number,
    discount: { type: Number, default: 0 },
    deliveryCharges: { type: Number, default: 0 },
    total: Number
  },
       orderStatus: {
    type: String,
    enum: ["placed", "processing", "shipped", "delivered", "cancelled"],
    default: "placed",
    index: true
  },
        isPaid: {                    // Payment status
          type: Boolean,
          default: false
        },
        paidAt: Date,               // When payment was confirmed
        deliveredAt: Date,           // When order was delivered
      },
    { timestamps: true }  
 );

const Order = mongoose.model("Order", orders);

module.exports = Order;