const mongoose = require('mongoose');
const orderitemSchema = mongoose.Schema({
    bookId: {
        type: mongoose.Schema.Types.ObjectId, 
        ref: "Book",
        required: true
    },
    title: String,             // Book title (snapshot for order history)
    quantity: {              // Number of copies ordered
        type: Number,
        required: true,
        min: 1
    },
    price: Number            // Price at the time of order (snapshot)
},{ _id: false });
const addressSchema = mongoose.Schema({
    fullName: String,
    phone: String,  
    addressLine: String,
    city: String,
    state: String,
    pincode: String,
    country: String
}, { _id: false });

const orders=mongoose.Schema(
    {          // Auto-generated by MongoDB
        userId: {                      // Reference to Users collection
          type: mongoose.Schema.Types.ObjectId,
          ref: "User",
          required: true
        },
        items: [orderitemSchema],  // Array of ordered items
        shippingAddress: {type: addressSchema, required: true}, // Shipping address snapshot     
        paymentInfo: {
        method: {
         type: String,
         enum: ["CARD", "UPI", "COD", "WALLET"],
         required: true
        },
        status: {
         type: String,
         enum: ["pending", "paid", "failed", "refunded"],
         default: "pending"
       },
        // Razorpay specific — all 3 needed for signature verification + audits
      razorpayOrderId:   { type: String },   // from createOrder() — before payment
      razorpayPaymentId: { type: String },   // from frontend — after payment
      razorpaySignature: { type: String },   // store after verification for audit

      paidAt: { type: Date },               
      },
    pricing: {
    subtotal: Number,
    discount: { type: Number, default: 0 },
    deliveryCharges: { type: Number, default: 0 },
    tax:{type:Number,default:0},
    total: {type: Number, required: true}
  },
       orderStatus: {
    type: String,
    enum: ["placed", "processing", "shipped", "delivered", "cancelled"],
    default: "placed",
    index: true
  },
        shippingInfo: {
    carrier: String,              // e.g., "FedEx", "UPS", "DHL"
    trackingNumber: String,       // Tracking number from carrier
    estimatedDeliveryDate: Date,  // Estimated delivery date
    shippedAt: Date               // When order was shipped
  },
        deliveredAt: Date,           // When order was delivered
      },
    { timestamps: true }  
 );

const Order = mongoose.model("Order", orders);

module.exports = Order;